### ISSUE TITLE
Bug in import tag

### ISSUE THREAD

**Issue by ahuoguo** [titzer/wizard-engine#232]
The following code
```wat
(module $a
  (tag $yield (export "yield") )
)
(register "a")

(module
  (type $task (func))
  (type $cont (cont $task))
  
  (import "spectest" "print_i32" (func $print_i32 (param i32)))
  (tag $yield (import "a" "yield"))

  (elem declare func $task)

  (func $task
    (suspend $yield)
  )

  (func $run (export "run")
    (block $h
        (block $on_yield (result (ref $cont))
          (resume $cont (on $yield $on_yield)
            (cont.new $cont (ref.func $task)))
          (call $print_i32 (i32.const 42))
          (br $h)
        )
        (drop)
        (call $print_i32 (i32.const 1))
    )
  )
)
(invoke "run")
```
Wizard seems to parse incorrect Module information when `tag` is imported. It successfully runs when I remove `(import "a" "yield")` in `tag`.
```
> wasm -d try.wast -o  try.bin.wast &&  spectest.jvm -ext:stack-switching try.bin.wast
##+try.bin.wast
##-fail: try.bin.wast @ 21:2 expected valid module, got invalid: overflow import section, expected 32 bytes, read 32
```

Context:

I was trying to run this [stack switching wast file](https://github.com/WebAssembly/stack-switching/blob/main/proposals/stack-switching/examples/control-lwt.wast) on wizard and I received the following error message:
```
> wasm -d control-lwt.wast -o  control-lwt.bin.wast &&  spectest.jvm -ext:stack-switching control-lwt.bin.wast
##+control-lwt.bin.wast
Exception in thread "main" java.lang.NullPointerException
        at V3C_SpecTestInterpreter.doInstantiate(Unknown Source)
        at V3C_SpecTestInterpreter.doModule(Unknown Source)
        at V3C_SpecTestInterpreter.doCommand(Unknown Source)
        at V3C_SpecTestInterpreter.run(Unknown Source)
        at V3K_spectest.runTest(Unknown Source)
        at V3K_spectest.main(Unknown Source)
        at V3K_spectest.main(Unknown Source)
```

**Comment by titzer** [comment]
I looked into this and it seems like the stack-switching reference interpreter is not in agreement with the exception handling proposal's encoding of import/export tags.

**Comment by ahuoguo** [comment]
Thanks for looking into this! Fixed by https://github.com/WebAssembly/stack-switching/pull/102/commits/24eb152418abc9c119556cbb9c1b2e457b2cc987
